# @package _global_

defaults:
  - _self_

model:
  _target_: src.models.module.LitModule
  
  # Model architecture (to be specified by concrete generative model)
  net:
    _target_: null # set your model class here, e.g., src.models.components.your_model.YourModel
    # model-specific parameters go here
  
  # Optimizer configuration
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.001
    weight_decay: 0.0
  
  # Learning rate scheduler
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: true
    mode: min
    factor: 0.5
    patience: 10
    min_lr: 1e-6
  
  # Training configuration (step-based regime)
  max_steps: 100000 # maximum number of training steps
  log_every_n_steps: 100 # log metrics every n steps
  val_check_interval: 1000 # run validation every n steps
  
  # Compilation
  torch_compile: false # whether to compile the model with torch.compile