defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss_best"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss_best"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1

periodic_inference:
  _target_: src.callbacks.periodic_inference.PeriodicInferenceCallback
  interval_steps: 1000
  max_batches: 1
  log_outputs: false
